Пытаюсь подключить Hibernate и добавить запись в таблицу Factory, но соединение не происходит. Из ошибки видно, что объект создаётся корректно, но строка entityManager.persist(employee) выдаёт ошибку:
INFO: HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
try1
try2
try3
catch
finalyy
org.example.entity.Stuff@17fede14
java.lang.IllegalArgumentException: Unknown entity type: org.example.entity.Stuff
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:700)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:681)
	at org.example.hibernarte_crud.Factory.main(Factory.java:24)
Caused by: org.hibernate.UnknownEntityTypeException: Unknown entity type: org.example.entity.Stuff
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.getEntityDescriptor(MappingMetamodelImpl.java:341)
	at org.hibernate.internal.AbstractSharedSessionContract.requireEntityPersister(AbstractSharedSessionContract.java:1000)
	at org.hibernate.internal.SessionImpl.getEntityPersister(SessionImpl.java:1535)
	at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:313)
	at org.hibernate.event.internal.EntityState.getEntityState(EntityState.java:62)
	at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:84)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:76)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:52)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:140)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:697)
	... 2 more

Process finished with exit code 0